### ISSUE TITLE
Violation of clean architecture principles

### ISSUE THREAD

**Issue by akshayshah2050** [mmacneil/CleanAspNetCoreWebAPI#2]
Hi I am using this source code as a reference to implementing clean architecture in ASP.NET Core 2.1 MVC.
In this code the validation logic for api request models is written in the presentation layer e.g. (RegisterUserRequestValidator) which contradicts the rule that business logic should be in domain layer

**Comment by mmacneil** [comment]
Thanks for sharing your opinion @akshayshah2050 

I wouldn't necessarily include model validation as part of the core business logic.  The purpose of model validation in the presentation layer is to act as a "frontline" check of the incoming data from the client to make sure it is valid before doing any further processing.  Usually, this is where we do superficial checks for non-empty strings, valid email addresses, properly formatted phone numbers and so on.  Ensuring the data is in a valid shape before sending to the core/domain layer for further processing/validation.

I usually like to think of validation as being a ubiquitous responsibility that happens across multiple layers of my application, not just one.

**Comment by akshayshah2050** [comment]
Ok thanks for the explanation
With your repository as the main reference and other sources from all over the internet i have created this repository : https://github.com/akshayshah2050/AspNetCoreWebApiWithCleanArcitecture
This is the very initial version of what i plan to create. Can u please review the project structure and other architectural aspects of the repository and provide your suggestions? I think it will help me in clarifying my concepts and doubts
Thanks in advance

**Comment by mmacneil** [comment]
Hi @akshayshah2050 - had a look through your project, well done!  It certainly looks like you've got a solid grasp on the importance of separating concerns and have implemented some great patterns in your code to achieve that.  One callout I would have on that topic is that you might want to consider further layering your project by adding separate class library projects to house your `Core` and `Infrastructure` layers.  This would just help to add the physical separation of layers in the solution.  This provides better de-coupling and can help make unit testing easier.  When you do this, your `Core` layer should have very few (if any) external dependencies as most of those will be found in your `Infrastructure` project (e.g. ORM/db access libraries, http client, cache client, logger etc.)

Hope this helps, keep up the good work!

Regards,
Mark

**Comment by akshayshah2050** [comment]
Thanks for your feedback
I am not quiet sure if i understand your suggestion correctly.
Core and Infrastructure layers in my repository are already implemented as .NET Core Class Libraries
Am i missing out on something???

**Comment by mmacneil** [comment]
Hahaha...sorry, yes you're right!  I first looked at your repo on my mobile device and for some reason thought your `Core` and `Infrastructure` folders were inside your web API project folder, but you're correct - they're separate, and that is the correct structure in my opinion.  

Keep up the good work!
